---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones
    enforce_order: false
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN
    email: env/CLOUDFLARE_EMAIL

zones:
  saifabdelrazek.com.:
    sources:
      - config
    targets:
      - cloudflare
