name: test

on: ["push", "pull_request"]

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3"
      - name: Install OctoDNS
        run: |
          pip install 'octodns==0.9.10'
          pip install octodns-cloudflare
      - name: Set executable permissions for dry-run
        run: chmod +x ./bin/dry-run
      - name: Do a dry run
        run: ./bin/dry-run
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
